version: 2.1
jobs:
  test:
    docker:
      - image: markusleroux/llvm-cabal:0.0.1
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --init --recursive
      - restore_cache:
          name: Restore Cached Artifacts
          key: haskell-artifacts-{{ checksum "compiler.cabal" }}
      - run:
          name: Update dependencies
          command: cabal update && cabal install --lib
      - run:
          name: Compile
          command: cabal build
      - run:
          name: Build tests
          command: cabal build --enable-tests
      - save_cache:
          name: Cache Artifacts
          key: haskell-artifacts-{{ checksum "compiler.cabal" }}
          paths:
            - "/root/.cabal"
            - "dist-newstyle"
      - run:
          name: Run Tests
          command: cabal new-test --enable-tests --test-show-details=streaming
workflows:
  test-flow:
    jobs:
      - test
